rootProject.name = "libnetty"
include(":libnetty-bom")
include(":libnetty-example")
include(":libnetty-fastcgi")
include(":libnetty-handler")
include(":libnetty-http")
include(":libnetty-http-client")
include(":libnetty-http-server")
include(":libnetty-http2-client")
include(":libnetty-http2-server")
include(":libnetty-resp")
include(":libnetty-resp3")
include(":libnetty-transport")
